config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/login' => 'sessions#new' 
  post '/login' => 'sessions#create' 
  post '/logout' => 'sessions#destroy' 
  root 'welcome#home' 
  resources :tool_orders
  resources :plant_orders
  resources :orders
  resources :locations
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :plants, only: [:index, :show]
  resources :tools, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord 
    has_many :orders 
    has_many :users, through: :orders 
    has_many :plants_orders, through: :orders 
    has_many :tools_orders, through: :orders 
    belongs_to :user 
end 

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :location 
    belongs_to :plant 
    belongs_to :tool

    def price 
        self.price = self.plant.price + self.tool.price
    end 

    def weight 
        self.weight = self.plant.weight + self.tool.weight
    end
end

app/models/plant.rb
class Plant < ApplicationRecord 
    has_many :orders 
    has_many :users, through: :orders 
    has_many :tools, through: :orders 
    has_many :locations, through: :orders
end 

app/models/tool.rb
class Tool < ApplicationRecord
    has_many :orders
    has_many :users, through: :orders 
    has_many :plants, through: :orders 
    has_many :locations, through: :orders 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :orders 
    has_many :locations
    has_many :plants, through: :orders 
    has_many :tools, through: :orders  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index 
        @user = current_user
        @locations = @user.locations
    end 

    def show 
        @user = current_user
        @locations = @user.locations.find(params[:id]) 
    end

    def new 
        @location = Location.new
        @users = [] 
        @users << current_user 
    end 

    def create 
        @location = Location.create(location_params)
        redirect_to location_path(@location)
    end

    private 
    def location_params 
        params.require(:location).permit(:name, :state, :city, :country, :street, :zipcode, :apartment, :user_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index 
        @user = current_user
        @orders = @user.orders 
    end 

    def show 
        @order = Order.find(params[:id]) 
    end 

    def new 
        @users = [] 
        @users << current_user 
        @plants = Plant.all 
        @tools = Tool.all
        @order = Order.new 
    end 

    def create 
        @order = Order.create(order_params) 
        redirect_to order_path(@order) 
    end 

    def edit 
        @order = Order.find(params[:id]) 
        @locations = Location.all 
        @users = User.all 
    end 

    def update 
        @order = Order.find(params[:id]) 
        @order.update(order_params)
        redirect_to order_path(@order) 
    end 

    def destroy 
        @order = Order.find(params[:id]) 
        @order.destroy 
        redirect_to orders_url 
    end 

    private 

    def order_params 
        params.require(:order).permit(:date, :arrival_estimate, :location_id, :user_id, :plant_id, :tool_id, :total_price, :tax, :shipping_fee, :weight, :order_status) 
    end 
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    def index 
        @plants = Plant.all
    end 

    def show 
        @plant = Plant.find(params[:id])
    end 
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
    def index 
        @tools = Tool.all
    end 

    def show 
        @tool = Tool.find(params[:id])
    end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/plant_orders_helper.rb
module PlantOrdersHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/tool_orders_helper.rb
module ToolOrdersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/locations/_form.html.erb
<%=form_for @location do |f|%>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div> 
    <div class="field"> 
        <%= f.hidden_field :user_id, :value => current_user.id %>  
    </div> 
    <div class="field">
        <%= f.label :street %>
        <%= f.text_field :street %>
    </div> 
    <div class="field">
        <%= f.label :apartment %>
        <%= f.text_field :apartment %>
    </div> 
    <div class="field"> 
        <%= f.label :city %>
        <%= f.text_field :city %>
    </div> 
    <div class="field"> 
        <%= f.label :state %>
        <%= f.text_field :state %>
    </div> 
    <div class="field"> 
        <%= f.label :country %>
        <%= f.text_field :country %>
    </div>
    <div class="field">
        <%= f.label :zipcode %>
        <%= f.number_field :zipcode %>
    </div> 
    <div class="actions"> 
        <%= f.submit %>
    </div> 
<% end %>

app/views/locations/edit.html.erb
    <div class="container"> 
    <h1>Edit Location/h1> 

    <%= render 'form'%> 
</div> 

app/views/locations/index.html.erb
<h1>My Locations</h1>
<%@user.locations.each do |p|%>
    <div><%= p.apartment%> <%=p.street%>, <%=p.city%>, <%=p.state%>, <%=p.country%>, <%=p.zipcode%>
    <%= link_to 'View', p %> 
    </div> 
<%end%>
    <%= button_to 'Back', plants_url ,  method: :get %> 
    


    

app/views/locations/new.html.erb
<h1> Create Location </h1>  
<%=form_for @location do |f|%>

    <%= f.label :street %>
    <%= f.text_field :street %>

    <%= f.label :apartment %>
    <%= f.text_field :apartment %>

    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :state %>
    <%= f.text_field :state %>

    <%= f.label :country %>
    <%= f.text_field :country %>

    <%= f.label :zipcode %>
    <%= f.number_field :zipcode %>

    <%= f.submit %>

    <%end%>

app/views/locations/show.html.erb
<div class="location">
    <h1><%=@locations.name %></h1>
    <h3><%=@locations.apartment%></h3>
    <h3><%=@locations.street%></h3>
    <h3><%=@locations.city%></h3>
    <h3><%=@locations.state%></h3> 
    <h3><%=@locations.zipcode%></h3>
    <h3><%=@locations.country%></h3> 
    <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d12086.416838998393!2d-73.57706865!3d40.770729100000004!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1463123119788" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    <%= button_to 'Delete', locations_path, method: :delete, data: { confirm: 'Are you sure you want to delete this location?' } %> 

    <%= button_to 'Edit', edit_location_path, method: :get %>
    <%= button_to 'Back', locations_path, method: :get %>
</div> 

app/views/orders/_form.html.erb
<%= form_for @order do |f| %> 
    <div class="field"> 
        <%= f.label :date %> 
        <%= f.date_field :date %> 
    </div> 
    <div class="field"> 
        <%= f.label :location_id %> 
        <%= f.collection_select :location_id, current_user.locations, :id, :name %>  
    </div> 
    <div class="field"> 
        <%= f.hidden_field :user_id, :value => current_user.id %>  
    </div> 
    <div class="field"> 
        <%= f.label :plant_id %> 
        <%= f.collection_select :plant_id, @plants, :id, :common_name %>  
    </div> 
    <div class="field"> 
        <%= f.label :tool_id %> 
        <%= f.collection_select :tool_id, @tools, :id, :name %> 
    </div> 
    <div class="actions"> 
        <%= f.submit %> 
    </div> 
<% end %> 

app/views/orders/edit.html.erb
<div class="container"> 
    <h1>Edit Order</h1> 

    <%= render 'form'%> 
</div> 

app/views/orders/index.html.erb
<h1>Orders</h1> 

<div><%= link_to 'Create Order', new_order_path %></div> 
<br /> 

<table> 
    <thead> 
        <tr>  
            <th>Location</th> 
            <th>Plant</th> 
            <th>Tool</th> 
            <th>Price</th> 
            <th>Weight</th> 
            <th>Order Status</th> 
            <th></th> 
        </tr> 
    </thead> 
    <tbody> 
        <% @orders.each do |order| %> 
            <tr> 
                <td><%= order.location.name %></td> 
                <td><%= order.plant.common_name %></td> 
                <td><%= order.tool.name %> 
                <td><%= order.price %></td> 
                <td><%= order.weight %></td> 
                <td> 
                    <%= link_to 'View', order %> 
                    <%= link_to 'Edit', edit_order_path(order) %> 
                    <%= link_to 'Delete', order, method: :delete, data: { confirm: 'Are you sure you want to delete this order?' } %> 
                </td> 
            </tr> 
        <% end %> 
    </tbody> 
</table> 

app/views/orders/new.html.erb
<div class="container"> 
    <h1>New Order</h1> 

    <%= render 'form'%> 
</div> 

app/views/orders/show.html.erb
<div class="container"> 
    <h1>Show Order</h1> 

    <h3><%= @order.date %></h3> 

    <h3><%= @order.location.name %></h3>

    <h3><%= @order.plant.common_name %></h3>  

    <h3><%= @order.tool.name %></h3> 
    <h2><%= button_to "Back", orders_path, method: :get %></h2> 
</div>

app/views/plants/index.html.erb
<h1>Plants</h1>

<%@plants.each do |p|%>
    <div class="card">
    <p><%=link_to p.common_name, plant_path(p)%></p></div>
<%end%>
    
  

app/views/plants/show.html.erb
<h1> <%=@plant.common_name%> </h1>
<h2> <%=@plant.scientific_name%> </h2>
<div class="min_temp"><%=@plant.temperature_minimum%></div>
<div class="max_prec"><%=@plant.precipitation_maximum%></div>
<div class="min_prec"><%=@plant.precipitation_minimum%></div>
<div class="moisture"><%=@plant.moisture_use%></div>
<div class="serial"><%=@plant.serial%></div>
<div class="weight"><%=@plant.weight%></div>
<img class='plant-img' src="<%= @plant.image %>" alt="<%@plant.common_name%>">
<div class="button"><%=button_to "Back", plants_path, method: :get%></div> 

    

app/views/tools/index.html.erb
<h1>Tools</h1>
<table> 
   <thead> 
      <tr>
         <th>Name</th> 
         <th>Description</th> 
         <th>Weight</th> 
         <th>Price</th> 
         <th></th> 
      </tr> 
   </thead> 
   <tbody> 
      <% @tools.each do |tool| %> 
         <tr>
            <td><%= tool.name %></td>
            <td><%= tool.description %></td> 
            <td><%= tool.weight %></td> 
            <td><%= tool.price %></td> 
            <td><%= link_to 'View', tool %></td> 
         </tr> 
      <% end %> 
   </tbody>
</table> 

app/views/tools/show.html.erb
<div class="tool">
    <h1><%= @tool.name %></h1>
    <h2><%= @tool.weight %></h2>
    <p><%= @tool.description %></p>
    <img class='tool-img' src="<%= @tool.image %>" alt="<%@tool.name%>">
    <%=button_to "Back", tools_path, method: :get%> 
</div> 

app/views/welcome/home.html.erb
<h1>Welcome to Greenery</h1> 

<img class="greenery" src="https://media.wired.com/photos/5d8aab8bef84070009028d31/master/w_2560%2Cc_limit/Plant-Music-1162975190.jpg" width="600" height="600" /> 