config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/login' => 'sessions#new' 
  post '/login' => 'sessions#create' 
  post '/logout' => 'sessions#destroy' 
  root 'welcome#home' 
  resources :tool_orders
  resources :plant_orders
  resources :orders
  resources :locations
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :plants, only: [:index, :show]
  resources :tools, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord 
    has_many :orders 
    has_many :users, through: :orders 
    has_many :plants_orders, through: :orders 
    has_many :tools_orders, through: :orders 
    belongs_to :user 
end 

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :location 
    belongs_to :plant 
    belongs_to :tool

    def price 
        self.price = self.plant.price + self.tool.price
    end 

    def weight 
        self.weight = self.plant.weight + self.tool.weight
    end
end

app/models/plant.rb
class Plant < ApplicationRecord 
    has_many :orders 
    has_many :users, through: :orders 
    has_many :tools, through: :orders 
    has_many :locations, through: :orders
end 

app/models/tool.rb
class Tool < ApplicationRecord
    has_many :orders
    has_many :users, through: :orders 
    has_many :plants, through: :orders 
    has_many :locations, through: :orders 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :orders 
    has_many :locations
    has_many :plants, through: :orders 
    has_many :tools, through: :orders  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index 
        @user = current_user
        @locations = @user.locations
    end 

    def show 
        @user = current_user
        @locations = @user.locations.find(params[:id]) 
    end

    def new 
        @location = Location.new
        @users = [] 
        @users << current_user 
    end 

    def create 
        @location = Location.create(location_params)
        redirect_to location_path(@location)
    end

    private 
    def location_params 
        params.require(:location).permit(:name, :state, :city, :country, :street, :zipcode, :apartment, :user_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index 
        @user = current_user
        @orders = @user.orders 
    end 

    def show 
        @order = Order.find(params[:id]) 
    end 

    def new 
        @users = [] 
        @users << current_user 
        @plants = Plant.all 
        @tools = Tool.all
        @order = Order.new 
    end 

    def create 
        @order = Order.create(order_params) 
        redirect_to order_path(@order) 
    end 

    def edit 
        @order = Order.find(params[:id]) 
        @locations = Location.all 
        @users = User.all 
    end 

    def update 
        @order = Order.find(params[:id]) 
        @order.update(order_params)
        redirect_to order_path(@order) 
    end 

    def destroy 
        @order = Order.find(params[:id]) 
        @order.destroy 
        redirect_to orders_url 
    end 

    private 

    def order_params 
        params.require(:order).permit(:date, :arrival_estimate, :location_id, :user_id, :plant_id, :tool_id, :total_price, :tax, :shipping_fee, :weight, :order_status) 
    end 
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    def index 
        @plants = Plant.all
    end 

    def show 
        @plant = Plant.find(params[:id])
    end 
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
    def index 
        @tools = Tool.all
    end 

    def show 
        @tool = Tool.find(params[:id])
    end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/plant_orders_helper.rb
module PlantOrdersHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/tool_orders_helper.rb
module ToolOrdersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Greenery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <img class ="logo" src="images/logo.svg" alt="logo">
  </a>
    <nav>
      <ul class="nav__links">
        <li><%=link_to "Home", root_path%></li> 
        <li><%=link_to "Plants", plants_path%></li>
        <li><%=link_to "Tools", tools_path%></li>
        <li><%=link_to "Locations", locations_path%> 
        <ul><li><%= link_to "Create Location", new_location_path %></li></ul></li> 
        <li><%=button_to "Cart", orders_path, method: :get%></li> 
        <% if user_signed_in? %> 
          <li><%= link_to current_user.email, edit_user_registration_path %></li> 
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %> 
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li> 
        <% end %>
      </ul>
    </nav>
  </header>
    <% if(notice) %><p class="notice"><%= notice %></p><% end %> 
    <% if(alert) %><p class="alert"><%= alert %></p><% end %> 
    <%= yield %>
  </body>
</html>